/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodoIndexRouteImport } from './routes/todo/index'
import { Route as TodoCreateRouteImport } from './routes/todo/create'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as TodoTodoIdIndexRouteImport } from './routes/todo/$todoId/index'
import { Route as TodoTodoIdEditRouteImport } from './routes/todo/$todoId/edit'

const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoIndexRoute = TodoIndexRouteImport.update({
  id: '/todo/',
  path: '/todo/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoCreateRoute = TodoCreateRouteImport.update({
  id: '/todo/create',
  path: '/todo/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoTodoIdIndexRoute = TodoTodoIdIndexRouteImport.update({
  id: '/todo/$todoId/',
  path: '/todo/$todoId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoTodoIdEditRoute = TodoTodoIdEditRouteImport.update({
  id: '/todo/$todoId/edit',
  path: '/todo/$todoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/todo/create': typeof TodoCreateRoute
  '/todo': typeof TodoIndexRoute
  '/todo/$todoId/edit': typeof TodoTodoIdEditRoute
  '/todo/$todoId': typeof TodoTodoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/todo/create': typeof TodoCreateRoute
  '/todo': typeof TodoIndexRoute
  '/todo/$todoId/edit': typeof TodoTodoIdEditRoute
  '/todo/$todoId': typeof TodoTodoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/todo/create': typeof TodoCreateRoute
  '/todo/': typeof TodoIndexRoute
  '/todo/$todoId/edit': typeof TodoTodoIdEditRoute
  '/todo/$todoId/': typeof TodoTodoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/500'
    | '/auth/login'
    | '/auth/register'
    | '/todo/create'
    | '/todo'
    | '/todo/$todoId/edit'
    | '/todo/$todoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/500'
    | '/auth/login'
    | '/auth/register'
    | '/todo/create'
    | '/todo'
    | '/todo/$todoId/edit'
    | '/todo/$todoId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/500'
    | '/auth/login'
    | '/auth/register'
    | '/todo/create'
    | '/todo/'
    | '/todo/$todoId/edit'
    | '/todo/$todoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  TodoCreateRoute: typeof TodoCreateRoute
  TodoIndexRoute: typeof TodoIndexRoute
  TodoTodoIdEditRoute: typeof TodoTodoIdEditRoute
  TodoTodoIdIndexRoute: typeof TodoTodoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/create': {
      id: '/todo/create'
      path: '/todo/create'
      fullPath: '/todo/create'
      preLoaderRoute: typeof TodoCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/': {
      id: '/todo/'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/$todoId/edit': {
      id: '/todo/$todoId/edit'
      path: '/todo/$todoId/edit'
      fullPath: '/todo/$todoId/edit'
      preLoaderRoute: typeof TodoTodoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/$todoId/': {
      id: '/todo/$todoId/'
      path: '/todo/$todoId'
      fullPath: '/todo/$todoId'
      preLoaderRoute: typeof TodoTodoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/404' {
  const createFileRoute: CreateFileRoute<
    '/404',
    FileRoutesByPath['/404']['parentRoute'],
    FileRoutesByPath['/404']['id'],
    FileRoutesByPath['/404']['path'],
    FileRoutesByPath['/404']['fullPath']
  >
}
declare module './routes/500' {
  const createFileRoute: CreateFileRoute<
    '/500',
    FileRoutesByPath['/500']['parentRoute'],
    FileRoutesByPath['/500']['id'],
    FileRoutesByPath['/500']['path'],
    FileRoutesByPath['/500']['fullPath']
  >
}
declare module './routes/auth/login' {
  const createFileRoute: CreateFileRoute<
    '/auth/login',
    FileRoutesByPath['/auth/login']['parentRoute'],
    FileRoutesByPath['/auth/login']['id'],
    FileRoutesByPath['/auth/login']['path'],
    FileRoutesByPath['/auth/login']['fullPath']
  >
}
declare module './routes/auth/register' {
  const createFileRoute: CreateFileRoute<
    '/auth/register',
    FileRoutesByPath['/auth/register']['parentRoute'],
    FileRoutesByPath['/auth/register']['id'],
    FileRoutesByPath['/auth/register']['path'],
    FileRoutesByPath['/auth/register']['fullPath']
  >
}
declare module './routes/todo/create' {
  const createFileRoute: CreateFileRoute<
    '/todo/create',
    FileRoutesByPath['/todo/create']['parentRoute'],
    FileRoutesByPath['/todo/create']['id'],
    FileRoutesByPath['/todo/create']['path'],
    FileRoutesByPath['/todo/create']['fullPath']
  >
}
declare module './routes/todo/index' {
  const createFileRoute: CreateFileRoute<
    '/todo/',
    FileRoutesByPath['/todo/']['parentRoute'],
    FileRoutesByPath['/todo/']['id'],
    FileRoutesByPath['/todo/']['path'],
    FileRoutesByPath['/todo/']['fullPath']
  >
}
declare module './routes/todo/$todoId/edit' {
  const createFileRoute: CreateFileRoute<
    '/todo/$todoId/edit',
    FileRoutesByPath['/todo/$todoId/edit']['parentRoute'],
    FileRoutesByPath['/todo/$todoId/edit']['id'],
    FileRoutesByPath['/todo/$todoId/edit']['path'],
    FileRoutesByPath['/todo/$todoId/edit']['fullPath']
  >
}
declare module './routes/todo/$todoId/index' {
  const createFileRoute: CreateFileRoute<
    '/todo/$todoId/',
    FileRoutesByPath['/todo/$todoId/']['parentRoute'],
    FileRoutesByPath['/todo/$todoId/']['id'],
    FileRoutesByPath['/todo/$todoId/']['path'],
    FileRoutesByPath['/todo/$todoId/']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  R500Route: R500Route,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  TodoCreateRoute: TodoCreateRoute,
  TodoIndexRoute: TodoIndexRoute,
  TodoTodoIdEditRoute: TodoTodoIdEditRoute,
  TodoTodoIdIndexRoute: TodoTodoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
